### ISSUE TITLE
GammaRay on Win 7 not displaying GUI

### ISSUE THREAD

**Issue by laboutpost2** [KDAB/GammaRay#166]
I successfully built GammaRay with MSVC 12 and Qt 5.4.0. I am able to use the launcher to select my process and attach, and a terminal window opens, displaying 

```
Detected ABI qt5.4-MSVC-release-i686, using ABI qt5.4-MSVC-release-i686.
```

The GammaRay GUI does not appear. Although I am able to interact with my program, the process will eventually terminate, displaying

```
Target not responding - timeout.
See <https://github.com/KDAB/GammaRay/wiki/Known-Issues> for troubleshooting
QThread: Destroyed while thread is still running
```

**Comment by asm-jaime** [comment]
For Qt 5.5 and Windows XP same problem.

**Comment by richbourne** [comment]
Same on Qt 5.5 on OSX.  No GUI at all.

**Comment by LangeSebastian** [comment]
Hey, we had the same problem
Did you build GammaRay (probe) in Debug/Release Mode (same as your application)?
Try launching the application using GammaRay. We could not inject into running application nor could we launch a debugging session (Debugger + GammaRay)

**Comment by krf** [comment]
@laboutpost2: Did you try latest 2.4 branch? @vkrause fixed some issues regarding attaching on Windows.

**Comment by richbourne** [comment]
I build the latest (GammaRay 2.4.0 (revision: 4d077f6) in Release mode) and I can neither attach nor launch a QT app built in Release mode.

+  The launch button is permanently disabled.
+  When I try and attach to a running instance the launcher GUI disappears but Gammaray remains running with no visible windows at all.

**Comment by freddan313** [comment]
Samme issue as previous users.

**Comment by gt6707a** [comment]
Have same issues. Launcher GUI doesn't work. Attach doesn't work from GUI or command line. The only way I got it to work is to launch from command line. ex: gammaray --probe PROBE_OF_CHOICE PATH_TO_QT_EXE\qt_app.exe.

**Comment by vkrause** [comment]
For the attaching problem, please test again with master at revision 1539a6ef75c588dba76d7347a340a13388d4d447 or newer, that contains a fix for a race on attaching that can result in the UI never showing up.

**Comment by akontsevich** [comment]
Have same issue, strange it worked for me previously. Will try 32 bit version as well.

**Comment by akontsevich** [comment]
Will this issue be solved?

**Comment by krf** [comment]
@akontsevich: Did you test with the latest GammaRay version? See https://github.com/KDAB/GammaRay/issues/166#issuecomment-208777768,

**Comment by akontsevich** [comment]
@krf, just pulled the latest version from master, rebuilt - does not work even on simple application.

> QObject::connect: Connecting from COMPAT signal (QProcess::error(QProcess::ProcessError))

**Comment by jcelerier** [comment]
Still can't make GammaRay work on OS X, with Qt 5.7

**Comment by steveire** [comment]
I hit this problem on Windows too with the windll and style injectors. 

When attempting to use the windll injector, there is no error message. When attempting to use the style injector, I get 

    Loading probe DLL failed: "Cannot load library /path/to/gammaray_probed.dll: The specified module could not be found."

The message "The specified module could not be found." comes from Qt when the `ERROR_MOD_NOT_FOUND` error is set on attempting to load the library. According to http://stackoverflow.com/questions/7661283/how-to-get-the-missing-dll-name-after-when-getlasterror-returns-error-mod-not and other locations on the internet, that is set when the specified dll **or its dependencies** can not be loaded.

There doesn't seem to be a way to convince windows to tell you which dependency is not found. There are external tools which developers can use to determine that, but not something suitable for building a good error message to show the user.

In my case at least, the problem is that gammaray_core and gammaray_common are not able to be loaded while attempting to load gammaray_probe. That is resolved when I put /path/to/gammaray/bin in my PATH environment variable, and I can use both injectors.

In attempting to produce a better diagnostic for this case, I tried using QLibrary to load those two dependencies in `Launcher::start` before calling `injector->launch`. Of course this does not work, because `Launcher::start` is part of `gammaray.exe`, and the dlls are in the same directory as that executable, loading them succeeds. However, the probe is loaded in a different process (and directory, most likely) and in that process, loading the dependencies fails.

Suggestions:

1) Modify the QSystemEnvironment passed to `injector->launch` such that the PATH environment variable gets `GammaRay::Paths::binPath()` appended. 

2) Consider modifying `WinDllInjector::inject()` and `InjectorStylePlugin::inject()` (and any other injector that works on Windows) to attempt to load the dependency dlls before attempting to load the probe, and issuing a better diagnostic to the user.

**Comment by vkrause** [comment]
Should be fixed in 2.7 and master now.

**Comment by laerne** [comment]
Still have this version on linux with GammaRay version 2.9.50 (revision: 66696d83)
