### ISSUE TITLE
Hangs when attached to a process on OSX 10.11.6

### ISSUE THREAD

**Issue by krasi-georgiev** [KDAB/GammaRay#292]
Here is how I installed it

```
git clone https://github.com/KDAB/GammaRay.git
mkdir build && cd build
brew install cmake  (version 3.7.1)
cmake ..
make
make install
```

I am QT 5.8 and when I start the program is shows that it found the 5.8 version but when I try to attach it to a process it just hangs.
After I click attach and the gammaray windows doesn't open

Here is a short video:
http://screencast.com/t/V7c76cBB

I tried debug and release builds with no difference

Please let me know if this is a bug or I am not doing something properly.

**Comment by krasi-georgiev** [comment]
now it starts , but the app crashes (tried 2 different QML apps)

Detected ABI qt5_8-x86_64, using ABI qt5_8-x86_64.
QML debugging is enabled. Only use this in a safe environment.
dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

Injector error: Process crashed


I tried this suggestion , but made no difference
export DYLD_INSERT_LIBRARIES='/System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine' 

http://stackoverflow.com/questions/22732381/dyld-symbol-not-found-but-nm-reports-otherwise-os-x-update-issue

**Comment by krasi-georgiev** [comment]
do you need anymore info for the issue ?

**Comment by krf** [comment]
Did you check -- with `nm` as suggested in the SO post -- whether GLEngine provides `_gliCreateContextWithShared`?

**Comment by krasi-georgiev** [comment]
yes I run
nm /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine

and one of the results shows
0000000000001485 T _gliCreateContextWithShared

**Comment by pasnox** [comment]
Can reproduce with latest macOS update + latest xcode + Qt 5.8 also.

> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                          	0x00007fff60632075 dyld_fatal_error + 1
1   dyld                          	0x00007fff60635094 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139
2   libdyld.dylib                 	0x00007fff8b56e262 dyld_stub_binder + 282
3   ???                           	0x0000000113b5d008 0 + 4625649672
4   com.apple.AppKit              	0x00007fff8f4fd843 -[NSOpenGLContext initWithFormat:shareContext:] + 80
5   libqcocoa.dylib               	0x000000010eba0659 0x10eb53000 + 317017
6   libqcocoa.dylib               	0x000000010eb5d413 0x10eb53000 + 42003
7   libQt5Gui.5.dylib             	0x000000010ae1e3db QOpenGLContext::create() + 59
8   libQt5Quick.5.dylib           	0x000000010a50d7c5 0x10a460000 + 710597
9   libQt5Quick.5.dylib           	0x000000010a50d169 0x10a460000 + 708969
10  libQt5Gui.5.dylib             	0x000000010adeeffb QWindow::event(QEvent*) + 763
11  libQt5Quick.5.dylib           	0x000000010a55a39c QQuickWindow::event(QEvent*) + 844
12  libQt5Widgets.5.dylib         	0x000000010a7fdb5d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 301
13  libQt5Widgets.5.dylib         	0x000000010a7fef01 QApplication::notify(QObject*, QEvent*) + 369
14  libQt5Core.5.dylib            	0x000000010b933494 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
15  libQt5Gui.5.dylib             	0x000000010ade3d64 QGuiApplicationPrivate::processExposeEvent(QWindowSystemInterfacePrivate::ExposeEvent*) + 308
16  libQt5Gui.5.dylib             	0x000000010adc6ff4 QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 404
17  libQt5Gui.5.dylib             	0x000000010adc5d6c QWindowSystemInterface::flushWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 572
18  libqcocoa.dylib               	0x000000010eb6576d 0x10eb53000 + 75629
19  libQt5Gui.5.dylib             	0x000000010adeb5f5 QWindow::setVisible(bool) + 1045
20  plplplplpl.BuggaRay           	0x000000010a4203fe PidTicker::PidTicker(QWidget*) + 1294
21  plplplplpl.BuggaRay           	0x000000010a41fd6c main + 412
22  libdyld.dylib                 	0x00007fff8b5705ad start + 1

**Comment by pasnox** [comment]
It looks like the latest macOS update does not longer tolerate DYLD_ FORCE FLAT_NAMESPACE=1.
Commenting code dealing with that and rebuilding GammaRay make it works again for me.
Though I did not tested it with oldest macOS / Qt version.

**Comment by pasnox** [comment]
Fixed

**Comment by krasi-georgiev** [comment]
giu still hangs when I try to attach to a prcess and in the terminal I am getting a different error

/Applications/GammaRay.app/Contents/MacOS/gammaray /Users/krasimir/projects/vipconsult/Qt/build-PortalChat-Desktop_Qt_5_8_0_clang_64bit-Debug/PortalChat.app/Contents/MacOS/PortalChat

Detected ABI qt5_8-x86_64, using ABI qt5_8-x86_64.
dyld: Library not loaded: @rpath/libgammaray_core-qt5_8-x86_64.2.7.0.dylib
  Referenced from: /Applications/GammaRay.app/Contents/PlugIns/gammaray/2.7/qt5_8-x86_64/gammaray_probe.dylib
  Reason: image not found
Injector error: Process crashed

**Comment by pasnox** [comment]
Are your sure the GUI hang is not caused by the new error now ?
This probe error is not related to the previous fix, it's a runtime issue, please open a new ticket for this one.
You can probably temporary bypass the probe error launching gammaray this way:
```
DYLB_LIBRARY_PATH=/path/to/the/libgammaray/folder gammaray -- your_app_and_args
```
If it's not enough, try harder with
```
DYLB_LIBRARY_PATH=/path/to/the/libgammaray/folder gammaray -- DYLB_LIBRARY_PATH=/path/to/the/libgammaray/folder your_app_and_args
```
The gdb error is fine, gdb is not available anymore on macOS, unless you installed it yourself.

**Comment by krasi-georgiev** [comment]
I don't see any other error, is there any way to enable debugging mode to give you more info ?

**Comment by pasnox** [comment]
There is not much info u can give us now, we have enough :)
Did you tried starting gammaray using the given env var DYLB_LIBRARY_PATH ?

**Comment by krasi-georgiev** [comment]
I tried this

DYLB_LIBRARY_PATH=/Applications/GammaRay.app/Contents/Frameworks /Applications/GammaRay.app/Contents/MacOS/gammaray -- /Users/krasimir/projects/vipconsult/Qt/build-PortalChat-Desktop_Qt_5_8_0_clang_64bit-Debug/PortalChat.app/Contents/MacOS/PortalChat

and this is the result
Detected ABI qt5_8-x86_64, using ABI qt5_8-x86_64.
dyld: Library not loaded: @rpath/libgammaray_core-qt5_8-x86_64.2.7.0.dylib
  Referenced from: /Applications/GammaRay.app/Contents/PlugIns/gammaray/2.7/qt5_8-x86_64/gammaray_probe.dylib
  Reason: image not found
Injector error: Process crashed

so it seems I am not passing the argyments correctly


this is the content of this folder

 ls /Applications/GammaRay.app/Contents/Frameworks
total 8208
lrwxr-xr-x   1 krasimir  admin    32B 17 Jan 01:21 libgammaray_launcher.dylib -> libgammaray_launcher.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin   236K 17 Jan 01:21 libgammaray_launcher.2.7.0.dylib
lrwxr-xr-x   1 krasimir  admin    48B 17 Jan 01:21 libgammaray_kitemmodels-qt5_8-x86_64.dylib -> libgammaray_kitemmodels-qt5_8-x86_64.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin    73K 17 Jan 01:21 libgammaray_kitemmodels-qt5_8-x86_64.2.7.0.dylib
lrwxr-xr-x   1 krasimir  admin    41B 17 Jan 01:21 libgammaray_core-qt5_8-x86_64.dylib -> libgammaray_core-qt5_8-x86_64.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin   1.6M 17 Jan 01:21 libgammaray_core-qt5_8-x86_64.2.7.0.dylib
lrwxr-xr-x   1 krasimir  admin    43B 17 Jan 01:21 libgammaray_common-qt5_8-x86_64.dylib -> libgammaray_common-qt5_8-x86_64.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin   254K 17 Jan 01:21 libgammaray_common-qt5_8-x86_64.2.7.0.dylib
lrwxr-xr-x   1 krasimir  admin    39B 17 Jan 01:21 libgammaray_ui-qt5_8-x86_64.dylib -> libgammaray_ui-qt5_8-x86_64.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin   982K 17 Jan 01:21 libgammaray_ui-qt5_8-x86_64.2.7.0.dylib
lrwxr-xr-x   1 krasimir  admin    30B 17 Jan 01:21 libgammaray_client.dylib -> libgammaray_client.2.7.0.dylib
-rwxr-xr-x   1 krasimir  admin   851K 17 Jan 01:21 libgammaray_client.2.7.0.dylib

**Comment by pasnox** [comment]
Ok, so the initial issue is then fixed.
The new issue is that not found image, please open a new issue for this one.

**Comment by krasi-georgiev** [comment]
are you sure I am using the correct parameters to start it ?

DYLB_LIBRARY_PATH=/Applications/GammaRay.app/Contents/Frameworks /Applications/GammaRay.app/Contents/MacOS/gammaray -- /Users/krasimir/projects/vipconsult/Qt/build-PortalChat-Desktop_Qt_5_8_0_clang_64bit-Debug/PortalChat.app/Contents/MacOS/PortalChat

**Comment by pasnox** [comment]
All is fine at this point yes (the dyld_library_path is even not needed normally, I just asked you to confirm the issue).
I'm locking this issue, please open a new one.
